### ISSUE TITLE
Backpressure

### ISSUE THREAD

**Issue by zeroware** [yelouafi/adtstream#1]
I'm still looking for an alternative to Rx.JS with backpressure handling. 

Is this something you plan to implement ?

**Comment by yelouafi** [comment]
AFAIK, backpressure implies 2 concepts : 

1- a pull or pausable stream
2- a write/output stream

For the 1st, for now only _push_ streams are supported (the Promise variant), which by essence are not pausable (for example we can't pause user mouse clicks). But i'm already thinking of how to integrate pull streams in the ADT model, i'm convinced that a Lazy variant is a perfect representation for the pull case.  but i'll still have to clarify my mind about the semantics of operations that involve more than 1 stream (for example merging a push and a pull stream together)

For the 2nd concept, i haven't yet thought about it, but now that you mention it i think we can still achieve backpressure-like semantics in writes on the terminal `forEach(action)` method: by having the action callback returns a promise we can delay subsequent writes (and by the way data retrieval from the pull stream) until the returned promise completes. But i don't know is that fits you use case (or if i missed your point).
